# Generated by Django 4.0.4 on 2022-04-25 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65, verbose_name='Título')),
                ('description', models.CharField(max_length=165, verbose_name='Descrição')),
                ('slug', models.SlugField()),
                ('preparation_time', models.IntegerField(verbose_name='Tempo de preparo')),
                ('preparation_time_unity', models.CharField(max_length=65, verbose_name='Tempo de preparo de unidade')),
                ('servings', models.IntegerField(verbose_name='Porções')),
                ('servings_unity', models.CharField(max_length=65, verbose_name='Unidade da porção')),
                ('preparation_step', models.TextField(verbose_name='Etapas de preparo')),
                ('preparation_step_is_html', models.BooleanField(default=False, verbose_name='HTML')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('cover', models.ImageField(upload_to='recipes/cover/%Y/%m/%d/', verbose_name='Imagem')),
                ('authro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.category', verbose_name='Categoria')),
            ],
        ),
    ]
