# Generated by Django 4.0.4 on 2022-04-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='authro',
            new_name='author',
        ),
    ]
