# Generated by Django 4.0.4 on 2022-05-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_category_alter_recipe_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='preparation_step',
            new_name='preparation_steps',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='preparation_step_is_html',
            new_name='preparation_steps_is_html',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='preparation_time_unity',
            new_name='preparation_time_unit',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='servings_unity',
            new_name='servings_unit',
        ),
    ]
